trigger:
  branches:
    include:
    - '*'
pr:
  branches:
     include:
     - '*'
jobs:
- job: Linux
  timeoutInMinutes: 360
  pool:
    vmImage: ubuntu-16.04

  steps:
  - template: linux-steps.yaml

